version: 2
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: Create Virtualenv
          command: make create-env
      - run:
          name: Activate Virtualenv
          command: make activate-env
      - run:
          name: Tests
          command: make test
