version: 2
jobs:
  build:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Tests
          command: python -u tests.py
